# A diretiva 'version' foi removida para alinhar com a especificação moderna do Compose.

services:
  # --- Banco de Dados para a API (PostgreSQL) ---
  db-api:
    image: postgres:15-alpine
    container_name: db-api-dev
    restart: unless-stopped
    volumes:
      - postgres_api_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Banco de Dados para o MLflow (PostgreSQL) ---
  db-mlflow:
    image: postgres:15-alpine
    container_name: db-mlflow-dev
    restart: unless-stopped
    volumes:
      - postgres_mlflow_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Servidor de Tracking do MLflow ---
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      db-mlflow:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5

  # --- API de Previsão ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db-api:
        condition: service_healthy
      mlflow-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_api_data_dev:
    driver: local
  postgres_mlflow_data_dev:
    driver: local
  mlflow_artifacts_dev:
    driver: local