services:
  db:
    image: postgres:13-alpine
    container_name: fiscal_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fiscal-net

  mlflow_server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: fiscal_mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns_data:/mlflow/artifacts
    depends_on:
      - db
    restart: unless-stopped
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      --default-artifact-root /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --log-level debug
    networks:
      - fiscal-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiscal_api_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - API_KEY=${API_KEY}
    depends_on:
      - mlflow_server # Removemos a condição de 'service_healthy' por enquanto
    restart: unless-stopped
    networks:
      - fiscal-net

volumes:
  postgres_data:

networks:
  fiscal-net:
    driver: bridge