services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # Carrega as variáveis de ambiente do ficheiro .env.local
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Esta variável continua aqui pois é usada no lado do cliente (browser)
      - NEXT_PUBLIC_API_URL=http://backend:8000

volumes:
  db_data:
