# docker-compose.yml (Versão Final com Cadeia de Saúde Completa)

services:
  db-mlflow:
    image: postgres:13
    container_name: db-mlflow
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MLFLOW}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MLFLOW}
      - POSTGRES_DB=${POSTGRES_DB_MLFLOW}
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data
    networks:
      - fiscal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_MLFLOW} -d ${POSTGRES_DB_MLFLOW}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-api:
    image: postgres:13
    container_name: db-api
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER_API}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API}
      - POSTGRES_DB=${POSTGRES_DB_API}
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - fiscal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_API} -d ${POSTGRES_DB_API}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0 --port 5000
      --backend-store-uri postgresql://${POSTGRES_USER_MLFLOW}:${POSTGRES_PASSWORD_MLFLOW}@db-mlflow:5432/${POSTGRES_DB_MLFLOW}
      --default-artifact-root /mlruns
    volumes:
      - ./mlruns_data:/mlruns
    networks:
      - fiscal-net
    depends_on:
      db-mlflow:
        condition: service_healthy
    # --- ADIÇÃO DO HEALTHCHECK PARA O MLFLOW SERVER ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 15s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mlruns_data:/mlruns
    networks:
      - fiscal-net
    # --- ALTERAÇÃO DA CONDIÇÃO DE DEPENDÊNCIA ---
    depends_on:
      mlflow-server:
        condition: service_healthy # <-- A MUDANÇA CRÍTICA
      db-api:
        condition: service_healthy

networks:
  fiscal-net:
    driver: bridge

volumes:
  mlflow_db_data:
  api_db_data: