services:
  db_api:
    image: postgres:13
    container_name: db_api
    environment:
      - POSTGRES_USER=${POSTGRES_USER_API}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API}
      - POSTGRES_DB=${POSTGRES_DB_API}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_api:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_API} -d ${POSTGRES_DB_API}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_mlflow:
    image: postgres:13
    container_name: db_mlflow
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MLFLOW}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MLFLOW}
      - POSTGRES_DB=${POSTGRES_DB_MLFLOW}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_mlflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_MLFLOW} -d ${POSTGRES_DB_MLFLOW}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fiscal_stability_api
    depends_on:
      db_api:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://${POSTGRES_USER_API}:${POSTGRES_PASSWORD_API}@db_api:5432/${POSTGRES_DB_API}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    depends_on:
      db_mlflow:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER_MLFLOW}:${POSTGRES_PASSWORD_MLFLOW}@db_mlflow:5432/${POSTGRES_DB_MLFLOW}
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri $$DATABASE_URL --default-artifact-root /mlruns

  dashboard:
    build:
      context: ./dashboard-fiscal-stability
      dockerfile: Dockerfile
    container_name: fiscal_stability_dashboard_react
    ports:
      - "8501:80"
    depends_on:
      - api

volumes:
  postgres_data_api:
  postgres_data_mlflow: