# =======================================================
# ARQUIVO DE ORQUESTRAÇÃO PARA PRODUÇÃO
# Local: Raiz do projeto (./docker-compose.yml)
# =======================================================

networks:
  fiscal_net:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - fiscal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fiscaldb
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fiscal_net

  mlflow:
    image: python:3.9-slim-buster
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://user:password@db:5432/fiscaldb
      - MLFLOW_ARTIFACT_LOCATION=/mlflow_artifacts
    volumes:
      - mlflow_artifacts:/mlflow_artifacts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fiscal_net
    command: >
      bash -c "pip install mlflow psycopg2-binary && mlflow server \
      --host 0.0.0.0 --port 5000 \
      --backend-store-uri postgresql://user:password@db:5432/fiscaldb \
      --default-artifact-root /mlflow_artifacts"

volumes:
  postgres_data:
  mlflow_artifacts: {}
