services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=/api
      - NEXTAUTH_URL=http://localhost:3000

volumes:
  db_data:
