# =======================================================
# ARQUIVO DE ORQUESTRAÇÃO PARA DESENVOLVIMENTO - FINAL
# Local: Raiz do projeto (./docker-compose.dev.yml)
# =======================================================

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=sua_string_secreta_aleatoria_aqui

volumes:
  node_modules:
