version: '3.8'

services:
  db_api:
    image: postgres:13
    container_name: db_api
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_api:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_mlflow:
    image: postgres:13
    container_name: db_mlflow
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password
      - POSTGRES_DB=mlflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_mlflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow_user -d mlflow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fiscal_stability_api
    depends_on:
      db_api:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    depends_on:
      db_mlflow:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://mlflow_user:mlflow_password@db_mlflow:5432/mlflow_db
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri $$DATABASE_URL --default-artifact-root /mlruns

  dashboard:
    build:
      # CORRIGIDO: Aponta para o diretório do projeto frontend.
      context: ./fiscal-dashboard
      dockerfile: Dockerfile.dev # Usa um Dockerfile específico para desenvolvimento
    container_name: fiscal_stability_dashboard_react
    ports:
      # CORRIGIDO: Mapeia a porta do Vite (5173) para a porta 8501 do seu computador.
      - "8501:5173"
    depends_on:
      - api
    # O volume permite que as alterações no seu código local sejam refletidas no contentor.
    volumes:
      - ./fiscal-dashboard:/app
      - /app/node_modules # Impede que o node_modules local sobrescreva o do contentor
    # Define a variável de ambiente para que o dashboard saiba onde encontrar a API.
    environment:
      - VITE_API_BASE_URL=http://api:8000

volumes:
  postgres_data_api:
  postgres_data_mlflow:
