channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.1.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.3.1
  - pyyaml==6.0.2
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
